// Generated by https://quicktype.io

export interface ITask {
    id:            number;
    date:          Date;
    type:          string;
    estimatedTime: Date;
    delegationId:  number;
    comments:      Comment[];
}

export interface Comment {
    content: string;
}
