// Generated by https://quicktype.io

export interface ITask {
    id:            number;
    date:          Date;
    type:          string;
    estimatedTime: Date;
    delegationId:  number;
    comments:      Comment[];
}

export interface Comment {
    content: string;
}

// Generated by https://quicktype.io

export interface ITaskGet {
    id:            number;
    date:          Date;
    state:         string;
    type:          string;
    estimatedTime: Date;
    delegationId:  number;
    comments:      Comment[];
    createdAt:     Date;
    updateAt:      Date;
    delegation:    Delegation;
}

export interface Comment {
    id:        number;
    content:   string;
    createdAt: Date;
    updateAt:  Date;
    taskId:    number;
}

export interface Delegation {
    id:       number;
    employee: Employee;
    consumer: Consumer;
}

export interface Consumer {
    id:         number;
    isCustomer: boolean;
    type:       string;
    person:     Person;
}

export interface Person {
    dni:       string;
    firstName: string;
    lastName:  string;
}

export interface Employee {
    id:       number;
    username: string;
    role:     string;
    person:   Person;
}
