// Generated by https://quicktype.io

export interface IClient {
    id: number,
    dni:        string;
    firstName:  string;
    lastName:   string;
    gender:     string;
    email:      string;
    address:    string;
    phone:      string;
    birthDate:  Date;
    locationId: number;
    consumer:   Consumer;
}

export interface Consumer {
    id:        number;
    type:       string;
    isCustomer: boolean;
}
