// Generated by https://quicktype.io

export interface IUser {
    id:         number;
    dni:        string;
    firstName:  string;
    lastName:   string;
    gender:     string;
    address:    string;
    phone:      string;
    email:      string;
    birthDate:  Date;
    locationId: number;
    location:   Location;
    employee:   Employee;
    createdAt:  Date;
    updateAt:   Date;
}

export interface Employee {
    id:             number;
    username:       string;
    hashedPassword: string;
    role:           string;
    isActive:       boolean;
    createdAt:      Date;
    updateAt:       Date;
    personId:       number;
}

export interface Location {
    id:   number;
    name: string;
}

export interface IUpdateUser {
    username: string;
    role:     string;
    person:   IUpdatePerson;
}



export interface IUpdatePerson {
    dni:        string;
    firstName:  string;
    lastName:   string;
    gender:     string;
    email:      string;
    address:    string;
    phone:      string;
    birthDate:  Date;
    locationId: number;
}


