// Generated by https://quicktype.io

export interface IChance {
    id:           number;
    amount:       number;
    date:         Date;
    delegationId: number;
}

// Generated by https://quicktype.io

export interface IChanceGet {
    id:           number;
    amount:       string;
    status:       string;
    date:         Date;
    createdAt:    Date;
    updateAt:     Date;
    delegationId: number;
    delegation:   Delegation;
}

export interface Delegation {
    id:         number;
    employeeId: number;
    consumerId: number;
    employee:   Employee;
    consumer:   Consumer;
}

export interface Consumer {
    id:         number;
    isCustomer: boolean;
    type:       string;
    person:     Person;
}

export interface Person {
    dni:       string;
    firstName: string;
    lastName:  string;
}

export interface Employee {
    id:       number;
    username: string;
    role:     string;
    person:   Person;
}
