// Generated by https://quicktype.io

export interface IDelegations {
    id: number;
    employeeId: number;
    consumerId: number;
}

export interface IDelegationsPost {
    employeeId: number;
    consumerId: number;
}
