
export interface IQuota {
    id:         number;
    startDate:  Date;
    endDate:    Date;
    amout:      number;
    comission:  string;
    achieved:   string;
    employeeId: number;
}

// Generated by https://quicktype.io

export interface IQuotaGet {
    id:         number;
    startDate:  Date;
    endDate:    Date;
    amout:      string;
    comission:  string;
    achieved:   string;
    createdAt:  Date;
    updateAt:   Date;
    employeeId: number;
    employee:   Employee;
}

export interface Employee {
    id:       number;
    username: string;
    role:     string;
    person:   Person;
}

export interface Person {
    dni:       string;
    firstName: string;
    lastName:  string;
}
