// Generated by https://quicktype.io


export interface IProduct {
  id:              number;
  codigoPrincipal: string;
  nombre:          string;
  descripcion:     string;
  urlImage:        string;
  existencia:      number;
  precioUnitario:  number;
  activo:          boolean;
}



