// Generated by https://quicktype.io

export interface IProduct {
  id:          number;
  name:        string;
  brand:       string;
  stock:       number;
  price:       number;
  description: string;
  category:    string;
}
